import { type PluginMeta } from "../../plugin.js"
import { type MeditreePlugin } from "../../server.js"
import { v4 as uuidv4 } from "uuid"

interface AdminAuthTokenPluginConfig {
  /**
   * The authentication token.
   * A uuid v4 will be generated by default.
   */
  token?: string
}

const AdminAuthTokenPlugin: PluginMeta<MeditreePlugin, AdminAuthTokenPluginConfig> = {
  create(config) {
    const token = config.token ?? uuidv4()
    return {
      setupMeditree: async ({ app, manager, container, service }) => {
      },
    }
  }
}
export default AdminAuthTokenPlugin
