import { type PluginMeta } from "../plugin.js"
import { type MeditreePlugin } from "../server.js"
import { v4 as uuidv4 } from "uuid"

interface AdminPluginConfig {
  /**
   * The authentication token.
   * A uuid v4 will be generated by default.
   */
  auth?: string
}

const AdminPlugin: PluginMeta<MeditreePlugin, AdminPluginConfig> = {
  create(config) {
    const auth = config.auth ?? uuidv4()
    return {
      setupMeditree: async ({ app, manager, container, service }) => {

      },
    }
  }
}
export default AdminPlugin
